AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  SendEmailFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 20
      Handler: app.handler
      Runtime: nodejs22.x
      Policies:
        - SESFullAccess
      CodeUri: .
      Environment:
        Variables:
          SENDER: "no-reply@wetwork.music"
          RECIPIENT: "wetworkva@gmail.com"
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            Path: /send-email
            Method: post
